### ISSUE TITLE
Error creating project, Python 3.10.4

### ISSUE THREAD

**Issue by Shane-Cotta** [py-universe/django-rest-cli#3]
`django-test % dr-cli startproject project_name
Traceback (most recent call last):
  File "/Users/shcotta/Desktop/django-test/venv/bin/dr-cli", line 5, in <module>
    from django_rest_cli.engine import entry_point
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/__init__.py", line 4, in <module>
    from django_rest_cli.engine.cli import main
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/cli/__init__.py", line 1, in <module>
    from .main import main
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/cli/main.py", line 3, in <module>
    from .cli_commands import CliCommands
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/cli/cli_commands.py", line 1, in <module>
    from django_rest_cli.engine.commands import AddCrud, StartApp, StartProject
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/commands/__init__.py", line 4, in <module>
    from .start_project import StartProject
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/commands/start_project.py", line 4, in <module>
    from django_rest_cli.engine.cli.mixins import ProjectConfigMixin
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/django_rest_cli/engine/cli/mixins.py", line 1, in <module>
    from examples import custom_style_3
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/examples/__init__.py", line 1, in <module>
    from PyInquirer import style_from_dict, Token
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/Users/shcotta/Desktop/django-test/venv/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)`

**Comment by nyior** [comment]
@Shane-Cotta  Thank you for bringing this to our attention. We will look into this and get back to you

**Comment by nyior** [comment]
This error is thrown by PyInquirer, the package we are using for managing command-line interactions. I saw that [an issue](https://github.com/CITGuru/PyInquirer/issues/181) regarding this has already been created on the repo. I will watch the thread for updates. In the meantime, I'd make it explicit that python 310 isn't supported yet. Thank you once again :)
